name: Basic Demo Deploy Application to AKS

on:
  workflow_dispatch: # Allow manual triggering

env:
  REGISTRY: ratifyacrdemo009.azurecr.io  # Updated to match Terraform ACR name
  CERT_NAME: ratify  # Updated to match Terraform certificate name
  AKV_NAME: ratifykvdemo009  # Updated to match Terraform Key Vault name

jobs:  
  deploy-app:
    name: Deploy Application to AKS
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_type:
          - name: demo-signed-image
            sign: true
          - name: demo-unsigned-image
            sign: false
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure CLI
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        az acr login --name $(echo $REGISTRY | cut -d'.' -f1)

    - name: Setup kubectl
      uses: azure/setup-kubectl@v4

    - name: Get AKS credentials
      run: |
        az aks get-credentials --resource-group ratifyrgdemo009 --name ratifyaksdemo009

    - name: Test Deploy ${{ matrix.image_type.name }} to AKS
      run: |
        kubectl run demo-signed --image=ratifyacrdemo009.azurecr.io/${{ matrix.image_type.name }}:latest --namespace demo