name: Basic Demo Notation Verify Image Signatures

on:
  workflow_dispatch: # Allow manual triggering

env:
  REGISTRY: ratifyacrdemo009.azurecr.io  # Updated to match Terraform ACR name
  CERT_NAME: ratify  # Updated to match Terraform certificate name
  AKV_NAME: ratifykvdemo009  # Updated to match Terraform Key Vault name

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_type:
          - name: demo-signed-image
          - name: demo-unsigned-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Log in to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name $(echo $REGISTRY | cut -d'.' -f1)

      - name: Setup notation
        uses: notaryproject/notation-action/setup@v1

      # Get Key ID dynamically from Azure Key Vault
      - name: Get Key ID from Azure Key Vault
        run: |
          KEY_ID=$(az keyvault certificate show -n ${{ env.CERT_NAME }} --vault-name ${{ env.AKV_NAME }} --query 'kid' -o tsv)
          echo "KEY_ID=$KEY_ID" >> "$GITHUB_ENV"
          echo "Retrieved Key ID: $KEY_ID"

      # Configure notation with the self-signed certificate
      # Verify the signed Helm chart in ACR
      - name: Notation Verify Helm Charts
        run: |
          # Download the certificate from Key Vault
          az keyvault certificate download --vault-name ${{ env.AKV_NAME }} --name ${{ env.CERT_NAME }} --file cert.pem --encoding PEM
          # Add the certificate to notation trust store using correct format
          notation cert add --type ca --store ca-certs cert.pem
          # Verify the certificate was added
          notation cert list --store ca
          # Import the trust policy
          notation policy import ./trustpolicy/demo-trustpolicy.json
          # Show trust policy
          notation policy show
          # Verify the image in ACR using digest for security
          notation verify ${{ env.REGISTRY }}/${{ matrix.image_type.name }}:latest