name: Notation Verify Image Signatures

on:
  workflow_dispatch: # Allow manual triggering

env:
  REGISTRY: ratifyacrdemo009.azurecr.io  # Updated to match Terraform ACR name
  CERT_NAME: ratify  # Updated to match Terraform certificate name
  AKV_NAME: ratifykvdemo009  # Updated to match Terraform Key Vault name

jobs:
  verify:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image_type:
          - name: demo-signed-image
          - name: demo-unsigned-image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup notation
        uses: notaryproject/notation-action/setup@v1

      - name: Setup trustpolicy
        run: |
          notation policy import ./trustpolicy/demo-trustpolicy.json
          notation policy show
  
      - name: Log in to Azure CLI
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
  
      - name: Log in to Azure Container Registry
        run: |
          az acr login --name $(echo $REGISTRY | cut -d'.' -f1)

      - name: Download public certificate from Key Vault
        run: |
          az keyvault certificate download --name ${{ env.CERT_NAME }} --vault-name ${{ env.AKV_NAME }} --file ./cert.pem

      - name: Add certificate to notation trust store
        run: |
          STORE_TYPE="ca-certs"
          STORE_NAME="default"
          notation cert add --type $STORE_TYPE --store $STORE_NAME ./cert.pem
          notation cert ls

      - name: Verify image signature
        uses: notaryproject/notation-action/verify@v1
        with:
          target_artifact_reference: ${{ env.REGISTRY }}/${{ matrix.image_type.name }}:latest